
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/ldd/Applications/CLion Nova.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 23.1.0 - arm64
...
